# batch size
g_batch_size: 64
d_batch_size: 64
e_batch_size: 256

# learning rate
lr: 0.0001

# noise dimension
zc_dim: 10
zn_dim: 30

# encoded class feature's dimension
fc_dim: 120

# the weight of znloss and zcloss
beta_1: 75
beta_2: 0.0005

# train and save step 
max_step  : 400
save_step : 50
test_step : 10

# whether use wgan-gp loss or not
wgan_gp: True

# the tempeture of zcloss 
temp_C: 0.07

# which gpu is choosed
gpu_id: 7
