# batch size for different model
g_batch_size: 150
d_batch_size: 300
e_batch_size: 300

# nosie dimension
zn_dim: 52
zc_dim: 3

# encoded feature dimension 
fz_dim: 52
fc_dim: 40

# image size
ch: 1
im_size: 64

# learning rate
g_lr: 0.001
d_lr: 0.002
e_lr: 0.001

# weights of closs and zloss
beta_zc: 1
beta_zn: 0.0001

temp_C: 0.07

# traing settings
max_step  : 300
chain_step: 100
save_step : 20
test_step : 10

critic: 1
_init: 'pytorch'
loss_metric: 'vanline'

# settings of additional labels
pretrain: True
r_batch_size: 100
real_critic: 5

# which gpu is choosed
gpu_id: 0