# batch size
g_batch_size : 128
d_batch_size : 64
ec_batch_size: 256
ez_batch_size: 32

# learning rate
lr: 0.0002

# noise dimension
zn_dim: 118
zc_dim: 10

# encoded class feature's dimension
fc_dim: 128

# the weight of znloss and zcloss
beta_1: 0.25
beta_2: 0.5

# train and save step 
critic    : 3
save_step : 50
chain_step: 100
test_step : 10
max_step  : 250

# which loss is choosed
loss_metric: 'hinge'

# the tempeture of zcloss 
temp_C: 0.07

# train mode
few_labels: True
pretrain: True
meta: False
use_ema: False

# aditional supervised data
r_batch_size: 100

# which gpu is choosed
gpu_id: 0

# adjust_lr
adjust_lr: True

# Pre-train model load paths
load_path: './cifar10_data/few_labels'

# few-label paths
few_labels_path: './cifar10_data/500_real_images.pt'

# Dataset name:
dataset_name: 'cifar10'