# batch size
g_batch_size: 64
d_batch_size: 64
e_batch_size: 300

# learning rate
lr: 0.0001

# noise dimension
zc_dim: 10
zn_dim: 40

# encoded class feature's dimension
fc_dim: 120

# the weight of znloss and zcloss
beta_1: 100
beta_2: 0.0005

# train and save step
max_step  : 300
save_step : 50
test_step : 10
chain_step: 200

# whether use wgan-gp loss or not
wgan_gp: True

# the tempeture of zcloss 
temp_C: 0.07

# train mode
few_labels: True
pretrain: True
meta: False  # pretrain with MAML

# aditional supervised data
r_batch_size: 50

# which gpu is choosed
gpu_id: 0

# adjust_lr
adjust_lr: False

# Pre-train model load paths
load_path: './fashionmnist_data/few_labels'

# few-label paths
few_labels_path: './fashionmnist_data/100_real_images.pt'

# Dataset name:
dataset: 'fashion'
# ema
use_ema: False

# critic G and 1 D
critic: 1