# batch size for different model
g_batch_size: 180
d_batch_size: 180
e_batch_size: 1500
r_batch_size: 30

# nosie dimension
zc_dim: 10
zn_dim: 118
fz_dim: 118
fc_dim: 128

# learning rate
lr: 0.0002

temp_C: 0.07

# weights of closs and zloss
beta_zc: 10
beta_zn: 10

num_c: 10

critic     : 3
max_step   : 600
save_step  : 50
chain_step : 200
real_critic: 6

interval   : 2
maxinterval: 20
alpha_init : 1


loss_metric : 'wgan-gp'
pretrain: True

# which gpu is choosed
gpu_id: 1